name: recipath
description: "An open-source app that helps you manage your recipes."

publish_to: 'none'

version: 1.6.8+30

environment:
  sdk: ^3.10.4

dependencies:
  sentry_flutter: ^9.6.0
  flutter:
    sdk: flutter  
  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  freezed: ^3.0.6
  go_router: ^17.0.1
  localstorage: ^6.0.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  random_string: ^2.3.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  file_picker: ^10.2.0
  share_plus: ^12.0.0
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  path: ^1.9.1
  duration_picker: ^1.2.0
  fl_chart: ^1.0.0
  mobile_scanner: ^7.0.1
  http: ^1.4.0
  url_launcher: ^6.3.2
  supabase_flutter: ^2.9.1
  logger: ^2.6.1
  flutter_image_compress: ^2.4.0
  dynamic_color: ^1.8.1
  purchases_flutter: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^9.0.0
  markdown_widget: ^2.3.2+8
  purchases_ui_flutter: ^9.4.0
  flutter_colorpicker: ^1.1.0
  wakelock_plus: ^1.4.0
  flutter_local_notifications: ^19.5.0
  receive_sharing_intent: ^1.8.1
  connectivity_plus: ^7.0.0

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.12.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
  json_serializable: ^6.9.5
  drift_dev: ^2.28.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets\images\empty.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: cunibon-games
